#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright &copy; 2014-2016 NetApp, Inc. All Rights Reserved.
#
# DO NOT EDIT THIS CODE BY HAND! It has been generated with jsvcgen.
#

import click

from element.cli import utils as cli_utils
from element.cli.cli import pass_context
from element.solidfire_element_api import SolidFireRequestException
from element import utils
import jsonpickle
import json

@click.group()
@pass_context
def cli(ctx):
    """Account methods."""
    ctx.sfapi = ctx.client

@cli.command('set', short_help="SetSnmpTrapInfo")
@click.option('--trap_recipients',
              type=SnmpTrapRecipient,
              required=True,
              help="List of hosts that are to receive the traps generated by the Cluster Master. At least one object is required if any one of the trap types is enabled. ")
@click.option('--cluster_fault_traps_enabled',
              type=bool,
              required=True,
              help="If "true", when a cluster fault is logged a corresponding solidFireClusterFaultNotification is sent to the configured list of trap recipients. ")
@click.option('--cluster_fault_resolved_traps_enabled',
              type=bool,
              required=True,
              help="If "true", when a cluster fault is logged a corresponding solidFireClusterFaultResolvedNotification is sent to the configured list of trap recipients. ")
@click.option('--cluster_event_traps_enabled',
              type=bool,
              required=True,
              help="If "true", when a cluster fault is logged a corresponding solidFireClusterEventNotification is sent to the configured list of trap recipients. ")
@pass_context
def set(ctx, trap_recipients, cluster_fault_traps_enabled, cluster_fault_resolved_traps_enabled, cluster_event_traps_enabled):
    """SetSnmpTrapInfo is used to enable and disable the generation of SolidFire SNMP notifications (traps) and to specify the set of network host computers that are to receive the notifications. The values passed with each SetSnmpTrapInfo method replaces all values set in any previous method to SetSnmpTrapInfo."""
    SetSnmpTrapInfoResult = ctx.element.set_snmp_trap_info(trap_recipients=trap_recipients, cluster_fault_traps_enabled=cluster_fault_traps_enabled, cluster_fault_resolved_traps_enabled=cluster_fault_resolved_traps_enabled, cluster_event_traps_enabled=cluster_event_traps_enabled)
    cli_utils.print_result(SetSnmpTrapInfoResult, as_json=ctx.json, depth=ctx.depth, filter_tree=ctx.filter_tree)

